# -*- coding: utf-8 -*-
"""Run the 5 direction checks on every dataset in the campaign.

    python tools/direction_sweep.py

Gate 6 requires that EVERY one of the 30 datasets passed its direction checks,
and until now only the watched seed had. The checks were run at stage 2 on seed
20250 and recorded in the gate 2 and gate 5 reports; the other 29 were generated
and trained without ever being asked whether the data points the right way.

This is the cheapest check in the build and the one most likely to catch a seed
that generated cleanly and still landed somewhere odd, because it asserts
orderings the design must produce rather than levels that a band can absorb.

Writes `docs/gates/direction_sweep.md` and returns non-zero if any dataset fails,
so a failure stops stage 6 rather than being read past.
"""
from __future__ import annotations

import json
import time
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import pandas as pd  # noqa: E402

from t9v2 import validate as V  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output"
SCALES = ["100K", "1M", "10M"]
SEEDS = list(range(20250, 20260))
NAMES = [n for n, _ in V.DIRECTION]


def one(path):
    """The 5 checks on one parquet. Returns {check: (ok, detail)}."""
    df = pd.read_parquet(path)
    try:
        return {n: fn(df) for n, fn in V.DIRECTION}
    finally:
        del df


def main():
    rows, failures, t0 = [], [], time.time()
    for scale in SCALES:
        for seed in SEEDS:
            p = OUT / ("t9v2_%s_seed%d.parquet" % (scale, seed))
            if not p.exists():
                rows.append((scale, seed, None, "PARQUET MISSING"))
                failures.append("%s seed%d: parquet missing" % (scale, seed))
                print("%-5s seed%d  PARQUET MISSING" % (scale, seed), flush=True)
                continue
            t = time.time()
            res = one(p)
            bad = [n for n in NAMES if not res[n][0]]
            rows.append((scale, seed, res, "PASS" if not bad else "FAIL"))
            if bad:
                failures.append("%s seed%d: %s" % (scale, seed, ", ".join(bad)))
            print("%-5s seed%d  %d/%d  %4.0fs  %s"
                  % (scale, seed, len(NAMES) - len(bad), len(NAMES),
                     time.time() - t, "PASS" if not bad else "FAIL " + str(bad)),
                  flush=True)

    n_pass = sum(1 for r in rows if r[3] == "PASS")
    md = ["# Direction-check sweep, all 30 datasets", "",
          "*Generated by `tools/direction_sweep.py`. This file is written, "
          "never edited.*", "",
          "Gate 6 requires every dataset to have passed its direction checks. "
          "Stage 2 checked the watched seed only; this sweep checks all 30, so "
          "the condition is measured rather than assumed.", "",
          "**%d of %d datasets pass all 5 checks.** Swept in %.0f seconds."
          % (n_pass, len(rows), time.time() - t0), "",
          "| Scale | Seed | " + " | ".join(NAMES) + " | Verdict |",
          "|---|---:|" + "---|" * (len(NAMES) + 1)]
    for scale, seed, res, verdict in rows:
        cells = (["-"] * len(NAMES) if res is None
                 else ["PASS" if res[n][0] else "**FAIL**" for n in NAMES])
        md.append("| %s | %d | %s | %s |"
                  % (scale, seed, " | ".join(cells), verdict))

    md += ["", "## The 5 checks", "",
           "| Check | What it asserts |", "|---|---|",
           "| `ltv_by_archetype_monotone` | mean e_ltv falls whale > engaged "
           "spender > casual > time filler > inactive |",
           "| `relevance_lifts_ctr` | CTR is higher on high-relevance rows |",
           "| `format_ecpm_ordering` | banner < interstitial < rewarded |",
           "| `adverse_selection` | lost rows are worth more than won rows, "
           "which is the selection C1 suffers |",
           "| `win_rises_with_bid_within_format` | bidding more wins more, "
           "held within each format |", ""]
    if failures:
        md += ["## Failures", ""] + ["- %s" % f for f in failures] + [""]
        md += ["A direction-check failure is read by the plan's rule: most or "
               "all seeds failing means a bug or an effect that is not there, "
               "and exactly one failing is sampling noise on a weak effect, "
               "read again at 1M and 10M.", ""]
    md.append("## Verdict\n\n**%s**\n" % ("PASS" if not failures else "FAIL"))

    d = ROOT / "docs" / "gates"
    d.mkdir(parents=True, exist_ok=True)
    (d / "direction_sweep.md").write_text("\n".join(md), encoding="utf-8")
    (d / "direction_sweep.json").write_text(
        json.dumps([{"scale": s, "seed": sd, "verdict": v,
                     "checks": ({n: bool(r[n][0]) for n in NAMES}
                                if r else None),
                     "detail": ({n: str(r[n][1]) for n in NAMES} if r else None)}
                    for s, sd, r, v in rows], indent=1), encoding="utf-8")

    print("\n%d of %d pass. %.0fs. Wrote docs/gates/direction_sweep.md"
          % (n_pass, len(rows), time.time() - t0))
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
