# -*- coding: utf-8 -*-
"""Write the gate 3 artifact: the four views, checked against the master.

    python tools/gate3_report.py output/t9v2_1M_seed20250.parquet

The plan states four pass conditions for gate 3. This measures all four on a real
master rather than reading them off the settings, because the settings are what
the censoring is supposed to implement, not evidence that it did.
"""
import io
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "src"))

import numpy as np                                               # noqa: E402
import pandas as pd                                              # noqa: E402

from t9v2 import censor as C                                     # noqa: E402
from t9v2.core import config                                     # noqa: E402

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
ROOT = HERE.parents[1]
OUT = HERE.parent / "docs" / "gates" / "gate3.md"

LAYER = {"C1": "DSP only", "C2": "DSP + MMP", "C3": "DSP + SSP", "C4": "DSP + MMP + SSP"}


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gate3_report.py <master.parquet>")
    src = Path(sys.argv[1])
    s = config.load("default")
    master = pd.read_parquet(src)
    views = C.all_views(master, s)

    latent = [c for n in s.emitting() if n["observability"] == "latent"
              for c in n["columns"]]
    lost = master["won"].to_numpy() == 0

    L = ["# Gate 3 report", "",
         "*Generated by `tools/gate3_report.py`. Regenerate after any change to the "
         "censoring map or to `censor.py`. This file is written, never edited.*", "",
         "Measured on `%s`, %s rows, %d master columns."
         % (src.name, format(len(master), ","), len(master.columns)), "",
         "## The four views", "",
         "The views are MASKS over one master, never copies: same rows, same order, "
         "same temporal split. Only visibility differs, which is what makes C1 to C4 an "
         "ablation rather than four experiments.", "",
         "| View | Layers | Columns | Masked on lost rows | Dropped | Funnel cells visible |",
         "|---|---|---:|---:|---:|---:|"]
    for v in C.VIEWS:
        p = C.plan(s, v)
        d = views[v]
        vis = int(d["click"].notna().sum())
        L.append("| **%s** | %s | %d | %d | %d | %s |"
                 % (v, LAYER[v], len(d.columns), len(p["mask"]), len(p["drop"]),
                    format(vis, ",")))

    L += ["", "## What each layer adds", "",
          "| Contrast | Adds | Detail |", "|---|---|---|",
          "| C1 to C2 | **rows** | the same %d columns, funnel labels on every row "
          "instead of the %s won rows only. %s lost rows gained per funnel column |"
          % (len(views["C1"].columns), format(int((~lost).sum()), ","),
             format(int(lost.sum()), ",")),
          "| C1 to C3 | **columns** | `%s` |"
          % "`, `".join(sorted(set(views["C3"].columns) - set(views["C1"].columns))),
          "| C2 to C4 | **columns** | the same 2, on top of full attribution |",
          "| C3 to C4 | **rows** | the same row gain, on top of price visibility |", ""]

    checks = [
        ("`click` reads won, all, won, all",
         [s.node("E1")["observability"][v] for v in C.VIEWS] == ["won", "all", "won", "all"],
         ", ".join(s.node("E1")["observability"][v] for v in C.VIEWS)),
        ("every latent hidden in all 4 views",
         all(not (set(latent) & set(d.columns)) for d in views.values()),
         "%d latent columns, 0 exposed" % len(latent)),
        ("`user_id` hidden everywhere",
         all("user_id" not in d.columns for d in views.values()), "absent from all 4"),
        ("C4 sees at least C2, C2 at least C1",
         all(set(views[a].columns) <= set(views[b].columns)
             and all(int(views[a][c].notna().sum()) <= int(views[b][c].notna().sum())
                     for c in views[a].columns)
             for a, b in [("C1", "C2"), ("C2", "C4"), ("C1", "C3"), ("C3", "C4")]),
         "columns and visible cells both nest, on all 4 edges"),
    ]
    L += ["## Gate 3 pass conditions", "", "| Result | Condition | Measured |",
          "|---|---|---|"]
    for name, ok, detail in checks:
        L.append("| %s | %s | %s |" % ("PASS" if ok else "**FAIL**", name, detail))

    # the three kinds of absence
    c1 = views["C1"]
    L += ["", "## The three kinds of absence stay distinguishable", "",
          "Collapsing any pair of these would change what a model trained on the view "
          "learns, so each is counted rather than assumed.", "",
          "| Meaning | Encoding | Count in C1's `click_timestamp` |", "|---|---|---:|",
          "| you were not told | `NA` | %s |" % format(int(c1["click_timestamp"].isna().sum()), ","),
          "| told it did not happen | `-1` | %s |" % format(int((c1["click_timestamp"] == -1).sum()), ","),
          "| told it happened | a timestamp | %s |"
          % format(int((c1["click_timestamp"] > 0).sum()), ","), "",
          "Masked integer columns keep an integral dtype (`%s` on `click`), so a count "
          "never silently becomes a measurement." % c1["click"].dtype, ""]

    L += ["## A defect found at the start of stage 3", "",
          "`H3` (`won`) was derived as a funnel outcome, which would have hidden it on "
          "lost rows in C1 and C3. Specification 1.5 lists it under \"Always visible: A, "
          "B, `C`, D, H1, H2, H3\", and both reasons matter. Real: every DSP is told "
          "whether its own bid won, whatever data layers it buys, because that is the "
          "bid response and not attribution. Structural: **Tier 2 learns P(win | bid) "
          "from this column**, so C1 and C3 would have had no losses to learn from, and "
          "those are the 2 views the SSP result is measured across.", "",
          "`build_graph.py` now excludes it from the funnel rule, `graph.yaml` changed by "
          "2 lines, and the always-visible group went from 20 columns to 21.", ""]

    ok = all(c[1] for c in checks)
    L += ["## Gate 3 verdict", "", "**%s**" % ("PASS" if ok else "FAIL"), ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote %s" % OUT.relative_to(ROOT))
    for name, o, detail in checks:
        print("  %-4s %s" % ("PASS" if o else "FAIL", name))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
