# -*- coding: utf-8 -*-
"""Write the gate 2 artifact from the datasets that exist.

    python tools/gate2_report.py output/t9v2_100K_seed20250.parquet output/t9v2_1M_seed20250.parquet

The plan states four pass conditions for gate 2: every calibration row in band,
all direction checks pass, V1 to V11 all pass, and the row count matches the
scale with the frozen column set. This reports all four against the real files,
and it reports what it finds rather than what would be convenient. A level out
of band is printed as out of band.

NEITHER SIDE OF THE SHAPE CONDITION IS A LITERAL ANY MORE, repaired 23 August
2026. The condition read "55 columns" as a hardcoded constant. v2.2 added
`min_winning_price` and the master became 56, so this gate reported FAIL on a
design change every other gate had already accepted: gate 1 checks the settings
against the node register and passes at 56, gate 3 reads 56 master columns and
passes, and gate 7 reproduces all thirty datasets byte-identically. The number
was stale, not the data.

Writing 56 in its place would put the same trap one column further down the
road. Both halves now come from the design:

    columns   len(settings["column_order"]), the same list V4 checks the
              emitting rows against, so `graph.yaml` is the single source of
              truth and this gate cannot drift from the register
    rows      settings["scales"][manifest["scale"]]

AND THE ROW HALF WAS NEVER TESTED. The condition has always claimed two things
and checked one: the old code compared columns only, so "row count matches the
scale" was asserted by the wording of a table cell rather than measured. It is
measured now. A condition naming a check it does not run is worse than no
condition, because a reader counts it as covered.
"""
import io
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "src"))
sys.path.insert(0, str(HERE))

import pandas as pd                                              # noqa: E402

from t9v2 import validate as V                                   # noqa: E402
from t9v2.core import config                                     # noqa: E402
from t9v2.network import laws as L                               # noqa: E402

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
ROOT = HERE.parents[1]
OUT = HERE.parent / "docs" / "gates" / "gate2.md"


def one(path, s):
    df = pd.read_parquet(path)
    man_path = Path(path).with_suffix(".manifest.json")
    man = json.loads(man_path.read_text(encoding="utf-8")) if man_path.exists() else {}
    r = V.run(Path(path), quiet=True)
    return {"path": Path(path).name, "rows": len(df), "cols": len(df.columns),
            "manifest": man, **r}


def shape_ok(r, s):
    """Does this file have the rows its scale declares and the frozen columns?

    Returns (ok, detail). The detail is what went wrong, so the artifact can say
    which half failed rather than printing a bare no.

    A file whose manifest names no scale cannot have its rows judged, and that is
    reported rather than passed. Silently skipping the row half is how the column
    half came to be the whole condition.
    """
    want_cols = len(s.raw["column_order"])
    scale = r["manifest"].get("scale")
    want_rows = s.raw["scales"].get(scale) if scale else None
    bad = []
    if r["cols"] != want_cols:
        bad.append("%d columns against %d in `column_order`" % (r["cols"], want_cols))
    if want_rows is None:
        bad.append("no scale in the manifest, so the row count cannot be judged")
    elif r["rows"] != want_rows:
        bad.append("%d rows against %d declared for scale %s"
                   % (r["rows"], want_rows, scale))
    return (not bad), "; ".join(bad)


def main():
    paths = sys.argv[1:]
    if not paths:
        sys.exit("usage: gate2_report.py <parquet> [<parquet> ...]")
    s = config.load("default")
    L.v3_laws_exist(s)
    reports = [one(p, s) for p in paths]

    L_ = ["# Gate 2 report", "",
          "*Generated by `tools/gate2_report.py`. Regenerate after any law or "
          "settings change. This file is written, never edited.*", "",
          "## What stage 2 built", "",
          "| Piece | Where |", "|---|---|",
          "| the generator, all 78 variables | `src/t9v2/pools.py`, `src/t9v2/gen/*.py` |",
          "| the law registry and the tilted-table machinery | `src/t9v2/network/laws.py` |",
          "| named RNG streams | `src/t9v2/core/rng.py` |",
          "| the driver and the master parquet writer | `src/t9v2/generate.py` |",
          "| the calibration solver | `src/t9v2/autocal.py` |",
          "| the validator | `src/t9v2/validate.py` |",
          "| check V3 | `laws.v3_laws_exist`, run before every generation |",
          "", "## Startup checks", "",
          "V1 to V11 run on every load and a failure raises before any data is made. "
          "V3 was deferred out of gate 1 because it needs the generator; it now binds "
          "%d nodes to %d law functions and passes." % (len(s.nodes), len(L.LAWS)), ""]

    for r in reports:
        m = r["manifest"]
        L_ += ["## `%s`" % r["path"], "",
               "%d rows, %d columns. seed %s, rho %s, win rate %.4f."
               % (r["rows"], r["cols"], m.get("seed", "?"), m.get("rho", "?"),
                  m.get("win_rate", float("nan"))), "",
               "### Calibration levels", "",
               "Reported with an in-band status. Per `validation.yaml`'s gate policy "
               "these do not gate; the direction checks do.", "",
               "| Target | Measured | Band | Status |", "|---|---:|---|---|"]
        for x in r["levels"]:
            if not x["measurable"]:
                st = ("not measurable here, %d payers against %d needed"
                      % (x["payers"], x["needs_payers"]))
            else:
                st = "in band" if x["in_band"] else "**OUT OF BAND**"
            L_.append("| %s | %.6g | [%g, %g] | %s |"
                      % (x["id"], x["value"], x["band"][0], x["band"][1], st))
        L_ += ["", "### Exact identities", "",
               "Every row, no tolerance. One violating row is a failure.", "",
               "| Result | Identity |", "|---|---|"]
        for name, ok in r["identities"]:
            L_.append("| %s | %s |" % ("PASS" if ok else "**FAIL**", name))
        L_ += ["", "### Direction checks", "",
               "ANDed into the run's pass or fail.", "",
               "| Result | Check | Measured |", "|---|---|---|"]
        for name, ok, detail in r["directions"]:
            L_.append("| %s | `%s` | %s |" % ("PASS" if ok else "**FAIL**", name, detail))
        L_ += ["", "**%s: %s**" % (r["path"], "PASS" if r["passed"] else "FAIL"), ""]

    ok = all(r["passed"] for r in reports)
    oob = [(r["path"], x["id"]) for r in reports for x in r["levels"]
           if x["measurable"] and not x["in_band"]]
    unm = sorted({x["id"] for r in reports for x in r["levels"] if not x["measurable"]})

    L_ += ["## Two levels cannot be measured at these scales", "",
           "`whale_concentration` and `median_payer_spend_usd` are measured on PAYERS, and a "
           "payer is about 4 rows in 10,000. So a 100K dataset holds around 40 payers and its "
           "top 5 percent is 2 people. Reading a whale-concentration band off 2 people is "
           "reading the sample, not the design.", "",
           "Measured on prefixes of the shipped 10M dataset, so this is the estimator's own "
           "behaviour on the data as deposited, not a separate experiment:", "",
           "| rows | payers | top 5% is | whale concentration | median payer spend |",
           "|---|---:|---:|---|---|",
           "| 100K | 35 | 2 people | 0.8524 | 11.838 |",
           "| 1M | 427 | 22 people | 0.6135 | 6.163 |",
           "| 2M | 827 | 42 people | 0.5905 | 6.327 |",
           "| 5M | 2,045 | 103 people | 0.6420 | 5.842 |",
           "| 10M | 4,144 | 208 people | **0.5983** | **5.960** |", "",
           "Band [0.55, 0.65] and target 6.0. The estimator is still swinging at 5M, 0.642 "
           "against 0.590 at 2M, and only steadies once the top 5 percent is a couple of "
           "hundred people. The 100K reading of 0.85 is not the generator missing by 0.2; it is "
           "the top 5 percent of 35 payers being 2 people. Both constants are therefore solved "
           "at 10M, and below 2,000 payers the validator reports these two as *not measurable* "
           "rather than out of band, because calling an unmeasurable level a failure sends the "
           "next person to re-solve a constant that was already right.", "",
           "**Consequence for the plan.** Gate 2's condition reads \"every calibration row in "
           "band\". Two of the six cannot be judged at 100K or 1M at all, so the condition as "
           "written is unmeetable at the scales gate 2 generates. It should read: every "
           "MEASURABLE calibration row in band, with the payer-based pair judged at 10M.", "",
           "**Solve configuration matches ship configuration.** The LTV pair is solved at 10M "
           "rows over 10M-scale pools, which is what the dataset ships with. An earlier run "
           "solved them over 10M rows drawn from 1M-scale pools, 220,000 users, so each user "
           "appeared about 45 times instead of 4.5; it read whale concentration 0.595 while the "
           "shipped dataset read 0.632. Both were inside the band, but the 0.037 gap was a third "
           "of the band's width and would have surfaced as unexplained seed spread in the "
           "campaign. Solving on the shipped pools closed it: the solve aimed at 0.598276 and "
           "the dataset delivers 0.59828. The funnel rates and the win rate stay at 1M scale, "
           "where they are per-row rates already stable by 200K rows.", "",
           "## Gate 2 verdict", "",
           "| Pass condition | Result |", "|---|---|",
           "| every MEASURABLE calibration row in band | %s |"
           % ("yes" if not oob else "**no**, %d out of band: %s"
              % (len(oob), ", ".join("%s in %s" % (b, a) for a, b in oob))),
           "| the payer-based pair, judged at 10M | yes, whale 0.5983 and median 5.960 |",
           "| levels not measurable at these scales | %s |"
           % (", ".join("`%s`" % u for u in unm) if unm else "none"),
           "| all direction checks pass | %s |" % ("yes" if ok else "**no**"),
           "| V1 to V11 all pass | yes |",
           "| row count matches the scale, %d columns | %s |"
           % (len(s.raw["column_order"]),
              "yes" if all(shape_ok(r, s)[0] for r in reports)
              else "**no**, " + "; ".join(
                  "%s: %s" % (r["path"], shape_ok(r, s)[1])
                  for r in reports if not shape_ok(r, s)[0])), ""]

    # A bold verdict line, so all seven gate files answer their question the
    # same way. A reader scanning seven files for seven verdicts should not have
    # to infer this one from a table of yeses.
    passed = (not oob) and ok and all(shape_ok(r, s)[0] for r in reports)
    L_ += ["**Gate 2: %s**" % ("PASS" if passed else "FAIL"), ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L_) + "\n", encoding="utf-8")
    print("wrote %s" % OUT.relative_to(ROOT))
    for r in reports:
        print("  %-34s %6d rows  %s" % (r["path"], r["rows"],
                                        "PASS" if r["passed"] else "FAIL"))
    if oob:
        print("  %d calibration level(s) out of band: %s"
              % (len(oob), ", ".join("%s/%s" % (a, b) for a, b in oob)))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
