# -*- coding: utf-8 -*-
"""Stage 7: write the datasheet that ships beside the 30 datasets.

    python tools/make_datasheet.py

Writes `docs/DATASHEET.md`.

GENERATED, NOT HAND-WRITTEN, and that is the point. The plan requires the
datasheet to carry EVERY value whose provenance route is `inferred`, meaning a
documented design judgement that no outside source backs. There are over a
hundred of them. A hand-written list would be correct on the day it was typed
and wrong at the next settings change, and the failure would be silent: a reader
would trust a list that had quietly stopped matching the data. Pulling the list
from the settings at write time means the datasheet cannot drift from what
actually generated the data.

The limitations section is hand-written, because it states what the data cannot
support, and that is a judgement no settings file holds.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from gate_report import leaves  # noqa: E402

GATES = ROOT / "docs" / "gates"


def main():
    from t9v2.core.config import load
    from t9v2 import generate as G
    s = load("default")

    rows = list(leaves(s.raw))
    by_route = {}
    for path, value, route, source in rows:
        by_route.setdefault(route, []).append((path, value, source))
    inferred = sorted(by_route.get("inferred", []))

    ck = json.loads((GATES / "checksums.json").read_text(encoding="utf-8")) \
        if (GATES / "checksums.md").exists() else {}
    n_data = ck.get("n_datasets", 0)
    gb = ck.get("total_bytes", 0) / 1e9

    md = ["# Datasheet — T9Sim v2 synthetic auction datasets", "",
          "*Generated by `tools/make_datasheet.py`. The inferred-values table is "
          "pulled from the settings at write time, so it cannot drift from what "
          "generated the data. This file is written, never edited.*", "",
          "## What this is", "",
          "%d synthetic datasets of mobile-game ad auctions: 10 seeds "
          "(20250-20259) at each of 100K, 1M and 10M impressions, %.1f GB in "
          "total. Each row is one bid request with its outcome, in 55 columns. "
          "Every dataset is generated from one specification by a deterministic "
          "process, so a seed reproduces byte for byte." % (n_data, gb), "",
          "They exist to support a controlled **ablation**: the marginal "
          "predictive value of integrated AdTech data layers, measured across "
          "four censored views over ONE ground truth.", "",
          "| View | Layers | What it adds |", "|---|---|---|",
          "| C1 | DSP only | the baseline; funnel outcomes on WON rows only |",
          "| C2 | DSP + MMP | **rows** — funnel outcomes on every row |",
          "| C3 | DSP + SSP | **columns** — `bid_density`, `winning_price` |",
          "| C4 | all three | both |", "",
          "The views are masks over one master, never separate draws. Same rows, "
          "same order, same temporal split; only visibility differs. That is "
          "what makes C1-C4 an ablation rather than four experiments.", "",
          "| | |", "|---|---|",
          "| settings hash | `%s` |" % (ck.get("settings_hash", "")[:32] or "-"),
          "| design fingerprint | `%s` |" % (ck.get("design_fingerprint")
                                             or G.fingerprint(s)),
          "| market | US, USD, first-price auctions |",
          "| genres | casual, hypercasual, strategy, rpg |",
          "| per-dataset checksums | `docs/gates/checksums.md` |", "",
          "---", "", "## What it must NOT be used for", "",
          "**It is not a measurement of any real market.** It is calibrated to "
          "iPinYou distribution SHAPES and rescaled to a 2025 US mobile-gaming "
          "market. iPinYou is Chinese desktop web display traffic from 2013. No "
          "number here should be quoted as a fact about mobile gaming, about US "
          "advertising, or about any named firm.", "",
          "**It cannot settle what is true of real data layers.** It can only "
          "show what follows FROM THIS GENERATOR. Every result is conditional on "
          "the data-generating process, and the SSP finding is the clearest "
          "case: SSP's value is null here because the rival-price structure this "
          "generator builds is largely reconstructible from public columns. A "
          "market whose private structure were stronger could give the opposite "
          "answer, and that is a property of the market, not a bug in the study.", "",
          "**Bid shading is out of scope.** The auction is first-price and no "
          "condition observes its own overpayment on wins: `winning_price` is "
          "the winner's own bid on won rows, and the competing bid "
          "`lu7_competing_bid` is latent in all four views. Nothing here "
          "supports a claim about shading strategy.", "",
          "**Do not treat the latent columns as features.** They exist so the "
          "evaluator has a yardstick. Training on `ev_truth`, "
          "`lu7_competing_bid` or any `LU`/`LA`/`LC` column measures the "
          "generator, not a model.", "",
          "**The payer-based statistics need scale.** A payer is about 4 rows in "
          "10,000, so a 100K dataset holds around 35 payers and its top 5 "
          "percent is 2 people. `whale_concentration` and "
          "`median_payer_spend_usd` are only meaningful at 10M, and are reported "
          "as *not measurable* below 2,000 payers rather than as failures.", "",
          "**Individual-level interpretation is meaningless.** There are no real "
          "people here. `user_id` is a synthetic index and is hidden from every "
          "view.", "",
          "---", "", "## Provenance", "",
          "Every calibratable value in the settings carries a route and a "
          "source. The full register is `docs/provenance.md`.", "",
          "| Route | Meaning | Count |", "|---|---|---:|"]
    meaning = {"quoted": "an outside source supplies the number",
               "auto-calibrated": "a solver output; its provenance is its target and solver",
               "inferred": "a documented design judgement, no outside source",
               "specified": "taken from a named T9 design document"}
    for r in ("quoted", "auto-calibrated", "inferred", "specified"):
        md.append("| **%s** | %s | %d |" % (r, meaning[r], len(by_route.get(r, []))))

    md += ["", "### The three inferred values that most shape the results", "",
           "Named here because they are design choices that a reader would "
           "otherwise assume were measured.", "",
           "| Value | Why it is a judgement |", "|---|---|",
           "| OS, OS-version and device-type shares | never checked against an "
           "outside source, and iPinYou cannot supply them, being desktop web "
           "traffic against a mobile-gaming market (open item O3 3a) |",
           "| archetype tilt strengths (tau) | archetype is T9's own latent and "
           "nothing external measures it. Every table is raked, so its marginal "
           "survives whatever tau is, which means no gate in the build can tell "
           "a right tau from a wrong one. The stage 4 sweep shows no headline "
           "contrast moves more than 2 seed standard deviations over tau x "
           "{0, 0.5, 1, 2}, which bounds the exposure without justifying the "
           "value (open item O3 3b) |",
           "| `ltv.base_median_usd`, the $6 median payer spend | relabelled from "
           "`quoted` to `inferred` on 15 August 2026: the project's own source "
           "register carries no such figure for the firms v1 cited |", "",
           "### Every inferred value", "",
           "All %d, pulled from the settings at write time. An inferred value is "
           "not a wrong value; it is one whose warrant is a documented judgement "
           "rather than an outside measurement, and that distinction is what "
           "this table exists to preserve." % len(inferred), "",
           "| Setting | Value | Source |", "|---|---|---|"]
    for path, value, source in inferred:
        v = str(value)
        if len(v) > 60:
            v = v[:57] + "..."
        md.append("| `%s` | %s | %s |" % (path, v, source or "-"))

    md += ["", "---", "", "## Reproducing it", "",
           "```", "python -m t9v2.campaign --scale 10M --seeds 20250", "```", "",
           "Generation is deterministic under the named-stream RNG scheme, and "
           "the claim is tested rather than asserted: stage 7 regenerates one "
           "seed at each scale into a temporary path and compares sha256 against "
           "the shipped file. See `docs/gates/checksums.md`.", "",
           "## Known limitations of the study, not the data", "",
           "- Gate 4 fails its click-AUC floor at 100K in C1 and C3 (0.5414 and "
           "0.5435 against a 0.55 floor) and passes at 1M. This is the censoring "
           "working as designed: those views see funnel labels on won rows only, "
           "so their click head trains on about 22,000 selected rows. It is "
           "reported as a failure at the scale the plan states it at rather than "
           "restated at the scale that passes.",
           "- Payer AUC in C1 and C3 rests on about 2,786 payer rows at 10M "
           "against C2 and C4's 16,696, and is the noisiest number reported.",
           "- The economics are counterfactual, scored against the master's own "
           "competing bid and floor. They are exact given the generator and say "
           "nothing about a real market's response to a changed bidding policy.",
           ""]

    (ROOT / "docs" / "DATASHEET.md").write_text("\n".join(md), encoding="utf-8")
    print("wrote docs/DATASHEET.md, %d inferred values listed" % len(inferred))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
