# -*- coding: utf-8 -*-
"""Aggregate per-seed SHAP attribution into one report.

    python tools/shap_aggregate.py --scale 10M --seeds 20250 20251 20252

Writes `docs/shap_attribution_<scale>_aggregate.{md,json}` from the per-seed
`shap_attribution_<scale>_seed<n>.json` files that `shap_1m.py` produced.

WHY THIS EXISTS. `shap_1m.py` takes one seed per invocation, inherited from v2
where the SHAP run was a single seed at 1M. Every other v2.2 result is reported
over seeds with a spread, and three standalone documents do not speak the way the
rest of the study speaks. Worse, the spread is the finding in at least one place:
the SSP share of the `click` head moves between 3.4 and 21.9 per cent across three
seeds, which nobody sees by reading three files in turn and nobody can miss in one
table.

MEAN AND RANGE, NOT A CONFIDENCE INTERVAL, AND `n` IS STATED IN THE DOCUMENT.
With three seeds a 95 per cent interval is t(2) = 4.30 wide and would imply a
precision this does not have. The house convention elsewhere is 1.96 SE over ten
seeds and this is deliberately NOT that, so it says so rather than looking like
it.

AGREEMENT IS COUNTED WHERE A DIRECTION EXISTS. For the price head's censored
against exact comparison every seed either moves a feature the same way or does
not, and `k/n` is the same statement `results_report.py` makes about its own
contrasts.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
VIEWS = ["C1", "C2", "C3", "C4"]
HEADS = ["click", "install", "payer", "spend", "price", "win"]


def is_ssp(feature):
    return feature.startswith("_enc_ssp")


def mean(xs):
    return sum(xs) / len(xs) if xs else float("nan")


def fmt_pct(xs):
    """mean, with the range beside it when the seeds disagree visibly."""
    if not xs:
        return "-"
    m, lo, hi = 100 * mean(xs), 100 * min(xs), 100 * max(xs)
    if hi - lo < 0.05:
        return "%.1f%%" % m
    return "%.1f%% [%.1f, %.1f]" % (m, lo, hi)


def load(scale, seeds):
    out = {}
    for s in seeds:
        p = DOCS / ("shap_attribution_%s_seed%d.json" % (scale, s))
        if not p.exists():
            raise SystemExit("missing %s" % p)
        out[s] = json.loads(p.read_text(encoding="utf-8"))
    return out


def collect(per_seed):
    """{view: {head: {feature: [share per seed]}}}, and the rank per seed."""
    shares, ranks = {}, {}
    for v in VIEWS:
        shares[v], ranks[v] = {}, {}
        for h in HEADS:
            sh, rk = {}, {}
            for s, res in per_seed.items():
                rows = res.get(v, {}).get(h)
                if not rows:
                    continue
                for i, r in enumerate(rows, 1):
                    sh.setdefault(r["feature"], []).append(r["share"])
                    rk.setdefault(r["feature"], []).append(i)
            if sh:
                shares[v][h], ranks[v][h] = sh, rk
    return shares, ranks


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--scale", default="10M")
    ap.add_argument("--seeds", type=int, nargs="+",
                    default=[20250, 20251, 20252])
    a = ap.parse_args(argv)

    per_seed = load(a.scale, a.seeds)
    n = len(a.seeds)
    shares, ranks = collect(per_seed)

    md = ["# SHAP attribution, %s, aggregated over %d seeds" % (a.scale, n), "",
          "*Generated by `tools/shap_aggregate.py`. This file is written, never "
          "edited.*", "",
          "Seeds %s. Mean absolute TreeSHAP, taken from the frozen bundles, "
          "50,000 sampled test rows per view per seed. Figures are the MEAN "
          "share across the %d seeds, with `[min, max]` beside it wherever the "
          "seeds disagree by more than a tenth of a point."
          % (", ".join(str(s) for s in a.seeds), n), "",
          "**n = %d, and that is fewer than this study reports elsewhere.** Every "
          "metric in `V2.2_Results.md` runs over ten seeds with a 95 per cent "
          "interval. Three seeds do not support one -- t(2) is 4.30 -- so this "
          "document gives a mean and an observed range and makes no interval "
          "claim. Read it as a diagnostic, not as a contrast with a verdict." % n,
          "",
          "**Units differ by head.** The four classifiers contribute in log-odds, "
          "`spend` in log-dollars, `price` in the AFT model's own log score. Raw "
          "contributions are therefore not comparable across heads, which is why "
          "every figure here is a share of its own head's total.", ""]

    # --- 1. SSP uptake
    md += ["---", "", "## 1. Do the SSP columns get used?", "",
           "C3 and C4 see `winning_price` and `bid_density`, which reach the "
           "model as the `_enc_ssp_*` encoders; C1 and C2 have no such columns. "
           "If the encoders sit at the bottom, the SSP columns are empty and the "
           "model ignored them. If the model reaches for them and the metric "
           "still does not move, they are REDUNDANT rather than empty.", "",
           "| Head | SSP share, C3 | SSP share, C4 | best rank, C3 |",
           "|---|---:|---:|---:|"]
    for h in HEADS:
        if h == "price":
            continue
        row = []
        for v in ("C3", "C4"):
            sh = shares[v].get(h)
            if not sh:
                row.append(None)
                continue
            per = []
            for i in range(n):
                per.append(sum(xs[i] for f, xs in sh.items()
                               if is_ssp(f) and len(xs) > i))
            row.append(per)
        rk = ranks["C3"].get(h) or {}
        best = [min((r[i] for f, r in rk.items() if is_ssp(f) and len(r) > i),
                    default=None) for i in range(n)]
        best = [b for b in best if b is not None]
        n_feat = len(shares["C3"].get(h) or {})
        md.append("| `%s` | %s | %s | %s |" % (
            h,
            fmt_pct(row[0]) if row[0] else "-",
            fmt_pct(row[1]) if row[1] else "-",
            ("%d-%d of %d" % (min(best), max(best), n_feat))
            if best and min(best) != max(best)
            else ("%d of %d" % (best[0], n_feat) if best else "-")))
    md += ["",
           "The `price` head is absent BY CONSTRUCTION. Its 20 features are "
           "identical in all four views, every SSP encoder barred from it by "
           "name, which is what makes its contrast a pure label-quality effect. "
           "There are no SSP columns in it to attribute.", ""]

    # --- 2. the price head, censored against exact
    p1, p3 = shares["C1"].get("price"), shares["C3"].get("price")
    if p1 and p3:
        deltas = {}
        for f in p1:
            a1, a3 = p1[f], p3.get(f, [0.0] * n)
            k = min(len(a1), len(a3))
            deltas[f] = [a3[i] - a1[i] for i in range(k)]
        order = sorted(deltas, key=lambda f: -abs(mean(deltas[f])))
        md += ["---", "",
               "## 2. What changes in the price head when the labels go exact",
               "",
               "The same twenty features in every view, so nothing here is a "
               "feature effect. C1 and C2 see only a BOUND on the clearing "
               "price, won rows below their bid and lost rows above it. C3 and "
               "C4 see the price itself. Every difference below is the model "
               "reacting to label quality alone.", "",
               "| Feature | C1, censored | C3, exact | change | seeds agreeing |",
               "|---|---:|---:|---:|---:|"]
        for f in order[:8]:
            d = deltas[f]
            same = sum(1 for x in d if (x > 0) == (mean(d) > 0))
            md.append("| `%s` | %s | %s | %+.1f pts [%+.1f, %+.1f] | %d/%d |"
                      % (f, fmt_pct(p1[f]), fmt_pct(p3.get(f, [0.0])),
                         100 * mean(d), 100 * min(d), 100 * max(d), same, n))
        md.append("")
        top1 = max(p1, key=lambda f: mean(p1[f]))
        top3 = max(p3, key=lambda f: mean(p3[f]))
        if top1 != top3:
            md += ["The head's leading feature changes on the mean, from `%s` "
                   "under censored labels to `%s` under exact ones."
                   % (top1, top3), ""]

    # --- 3. the full picture: every feature against every head, one view
    # C4 IS THE VIEW SHOWN because it is the only one holding every data layer,
    # so a feature missing here is missing because the model did not use it
    # rather than because the view could not see it. C1 is beside it so the
    # censored end of the ablation is visible in the same table.
    for view, why in (("C4", "all three data layers"), ("C1", "DSP only")):
        heads_here = [h for h in HEADS if shares[view].get(h)]
        allf = sorted({f for h in heads_here for f in shares[view][h]},
                      key=lambda f: -mean([mean(shares[view][h].get(f, [0.0]))
                                           for h in heads_here]))
        md += ["---", "",
               "## %s. Every feature, every head, %s (%s)"
               % (3 if view == "C4" else 4, view, why), "",
               "Mean share of its head's total attribution, over the %d seeds. "
               "Sorted by mean across the heads, so the features carrying the "
               "model are at the top. A dash means the feature is not in that "
               "head's list at all." % n, "",
               "| Feature | " + " | ".join("`%s`" % h for h in heads_here) + " |",
               "|---" + "|---:" * len(heads_here) + "|"]
        for f in allf:
            cells = []
            for h in heads_here:
                xs = shares[view][h].get(f)
                cells.append("-" if xs is None else "%.1f%%" % (100 * mean(xs)))
            mark = " *(SSP)*" if is_ssp(f) else ""
            md.append("| `%s`%s | %s |" % (f, mark, " | ".join(cells)))
        md.append("")

    # --- 5. compact orientation across all four views
    md += ["---", "", "## 5. Top three per head, all four views", "",
           "The same numbers as above, cut to the leaders, with C2 and C3 "
           "included. Every feature of every head and view is in the `.json` "
           "beside this file, per seed.", "",
           "| Head | View | 1st | 2nd | 3rd |", "|---|---|---|---|---|"]
    for h in HEADS:
        for v in VIEWS:
            sh = shares[v].get(h)
            if not sh:
                md.append("| `%s` | %s | *intercept, nothing to attribute* | | |"
                          % (h, v))
                continue
            top = sorted(sh, key=lambda f: -mean(sh[f]))[:3]
            cells = ["`%s` %.0f%%" % (f, 100 * mean(sh[f])) for f in top]
            while len(cells) < 3:
                cells.append("")
            md.append("| `%s` | %s | %s |" % (h, v, " | ".join(cells)))
    md.append("")

    out = {"scale": a.scale, "seeds": a.seeds, "n": n,
           "share_mean": {v: {h: {f: mean(xs) for f, xs in sh.items()}
                              for h, sh in shares[v].items()} for v in VIEWS},
           "share_per_seed": {v: {h: sh for h, sh in shares[v].items()}
                              for v in VIEWS}}
    stem = "shap_attribution_%s_aggregate" % a.scale
    (DOCS / (stem + ".md")).write_text("\n".join(md) + "\n", encoding="utf-8")
    (DOCS / (stem + ".json")).write_text(json.dumps(out, indent=1),
                                         encoding="utf-8")
    print("wrote docs/%s.md and .json  (n=%d)" % (stem, n))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
